#sudo: required

language: python

python: 2.7

# before_install:

install:
- pip install ansible==2.0.0.2
  # - pip install selenium nose
 
script:
  - cd server-maintenance && ansible-playbook tasks/main.yml --check
